name: Update Keycloak Version for NodeJS

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "New version of keycloak for NodeJS"
        required: true
        type: string

jobs:
  update-keycloak-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version of keycloak-connect
        id: get-current-version
        run: |
          CURRENT_VERSION=$(grep -oP '"keycloak-connect": "\K[^"]+' nodejs/resource-server/package.json)
          echo "Current version: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Check version difference
        id: check-version
        run: |
          if [ "${{ github.event.inputs.new_version }}" = "CURRENT_VERSION" ]; then
            echo "The version is already up-to-date."
            echo "update_needed=false" >> $GITHUB_ENV
          else
            echo "A version update is needed."
            echo "update_needed=true" >> $GITHUB_ENV
          fi

      - name: Update keycloak-connect version
        if: env.update_needed == 'true'
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          echo "Updating keycloak-connect to version $NEW_VERSION"
          sed -i 's|"keycloak-connect": "[^"]*"|"keycloak-connect": "'"$NEW_VERSION"'"|g' nodejs/resource-server/package.json

      - name: Configure Git
        if: env.update_needed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        if: env.update_needed == 'true'
        run: |
          git add nodejs/resource-server/package.json
          git commit -m "Update keycloak-connect for nodejs to version ${{ github.event.inputs.new_version }}"
          git push origin main